### ISSUE TITLE
README.md: The title link is broken

### ISSUE THREAD

**Issue by motet-a** [lodi-g/EPITECH_Sublime#3]
https://tektools.epi.codes/ is down.

**Comment by demaisj** [comment]
Hi,

We're aware of that issue. The only problem is that we haven't opened this website yet.

We have left this link here kind of as a reminder.

**Comment by lodi-g** [comment]
Btw if you want to donate a RPi 3 to power our server, feel free to do so 👌

**Comment by demaisj** [comment]
Closing since the site was never opened. Maybe I'll do a database for official epitech configurations & plugins one day.
